VS11: Update default value of _WIN32_WINNT to target Windows XP or later
This allows building VTK with Visual Studio 11 on Windows 8. Without this
change, you get this error when building the vtkGUISupportMFC module:

  C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\ATLMFC\INCLUDE\atlwinverapi.h(29) : fatal error C1189: #error :
  This file requires _WIN32_WINNT to be #defined at least to 0x0403. Value 0x0501 or higher is recommended.

All of these locations are protected with an #ifndef structure like this:

  #ifndef _WIN32_WINNT
  #define _WIN32_WINNT 0x0501 // 0x0501 means target Windows XP or later
  #endif

That way, if people building VTK really need to target older Windows
operating systems, (still?? really!!???) ... they can still do so by
defining _WIN32_WINNT themselves when building VTK and when including
VTK headers in their own applications.

Reference (what the various values of _WIN32_WINNT mean):
  http://msdn.microsoft.com/en-us/library/windows/desktop/aa383745%28v=vs.85%29.aspx

Change-Id: Ie86432d1388912a0e4321dac232a924aefa3720e