BUGFIX: Resolve issue with random mode and and setting of max no of pts.
Problem:
 If random mode is on and the maximum number of points has not been set
 then the following error is triggered due to an attempt being made to
 allocate a VTK_LARGE_ID array of points.

 ERROR: In ... vtkDataArrayTemplate.txx, line 144
 vtkFloatArray (00000000026EB980):
 Unable to allocate 9223372036854775805 elements of size 4 bytes.

 The failure is initially caused by this line:
 vtkIdType localMaxPts = this->MaximumNumberOfPoints;
 because numNewPoints has been set to VTK_LARGE_ID

Solution:
 A check has been inserted to ensure that if the maxium
 number of points exceeds the number of points in the input data then
 localMaxPts is clamped to the number of points in the input data.

The underlying assumption is that you cannot
mask more than the total number of points in the input.

Change-Id: Iffbcaacbd493d105df4151d771f2eb9ccc1039ba