Fix TextContextMathImage.
Matplotlib seems to need \left{ to be \left\{ in some cases?

Otherwise:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/matplotlib/textpath.py", line 137, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_mathtext(prop, s)
  File "/usr/lib/python2.7/site-packages/matplotlib/textpath.py", line 228, in get_glyphs_mathtext
    s, self.DPI, prop)
  File "/usr/lib/python2.7/site-packages/matplotlib/mathtext.py", line 3010, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/usr/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2344, in parse
    str(err)]))
ValueError:
\left{\frac{-b\pm\sqrt{b^2-4ac}}{2a}\right}
     ^
Expected a delimiter (at char 5), (line:1, col:6)
ERROR: In ../Rendering/Matplotlib/vtkMatplotlibMathTextUtilities.cxx, line 235
vtkMatplotlibMathTextUtilities (0x1cb8f70): Object is NULL!

Change-Id: I30d2e5eea46dafe670f1465c0b9afabea6b6c764